---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sopt.
--- DateTime: 6/18/23 00:00
---


if (redis.call('get', KEYS[1] == ARGV[1])) then
    return redis.call('del', KEYS[1])
end
return 0